### ISSUE TITLE
Missing "Objeto del Gasto" codes: change the breakdown logic

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#17]
Hey @cyberbikepunk , hope you’re doing all right.

So we’ve been checking the missing descriptions for the Objeto del Gasto extractions and we realized that the same rules don´t apply for every year. So I’ll try to explain these exceptions by year:

2008-2010
“Partida Específica” didn’t exist between 2008 and 2010. All codes are made of four digits so the rules of the extraction change a bit:
-   Capítulo: Extract the first of the four digits and multiply by 1000.
-   Concepto: Extract the first two of the four digits and multiply by 100.
-   Partida Genérica: It’s the same than the four digits code.

As an example you can watch the following picture:

![image](https://cloud.githubusercontent.com/assets/17733942/18112664/df02542a-6eee-11e6-9094-35b9cb280c4c.png)

2012
-   Up until now, we haven´t found the information regarding the 2012 missing codes, so we are searching for the description of the missing Partida Específica.

2016
The data set provided for 2016 doesn’t have “Objeto del Gasto” but “Concepto del Gasto” with a four digit number, so you won’t be able to extract Partida Específica and Genérica from it. In this case, you’ll only be able to extract Capítulo from the Concepto, because we can’t be certain that, for the rest of the year, the code will be a complete five digit number, until the year-end report. So, for 2016, you just have:
-   Capítulo: Extract the first of the four digits and multiply by 1000.
-   Concepto: stays the same as in the data set.

![image](https://cloud.githubusercontent.com/assets/17733942/18112672/f58871f2-6eee-11e6-9660-f3607e52cb93.png)

Can you please assure us that there won’t be missing spaces for the drill down in the Open Spending Viewer?, then we can leave the columns “ID_PARTIDA_GENERICA”, “DESC_PARTIDA_GENERICA”, “ID_PARTIDA_ESPECIFICA”, and “DESC_PARTIDA_ESPECIFICA” with all their spaces blank. If not, then we can exclude 2016 for the merging and publish 2016 until we finish with the Budget Proposal of 2017 we’re currently working on and upload it in a separate database. That way we “close” 2008-2015. And have a separate data base for 2016 (and the quarterly updates) in case we don’t have the full 5 digit number, and one last upload for Budget Proposal 2017.

If we are clear here, I’ll be eliminating from the excel document the missing codes for 2010 and 2016 (as for the rest of the years, we already filled the missing descriptions). You shouldn´t have any more issues with missing codes after applying these rules to 2010 and 2016.  

Please let me know if you have any questions.

Cheers!

**Comment by cyberbikepunk** [comment]
@Victordeleon let's try keeping it as one database by applying the above changes.. We need to first check that the pipeline returns a completely empty file of missing IDs. The "spaces" in the filter menus issue will be fixed [ seperately here](https://github.com/openspending/openspending/issues/1078) by @akariv

**Comment by cyberbikepunk** [comment]
@Victordeleon From my point of view: 
- 2010: the current algorithm is correct
- 2012 waiting for codes
- 2016 just fixed the algorithm

I'm going to run the pipeline again

**Comment by Victordeleon** [comment]
Hi @cyberbikepunk 

If you use the first rules we gave you for extracting 2010 you'll obtain wrong codes, the thing is that, from 2008 to 2010, the complete code consists of 4 digits and there wasn't a Partida Especifica concept.

Being that so, Capitulo and Concepto extraction rules remain the same as before. But, for Partida Generica you need to extract the four numbers instead of three of them. In this case there wouldn´t be any Partida Especifica. 

As for 2016, were still finding data for "Partida Genérica" which isn't correct
![image](https://cloud.githubusercontent.com/assets/17733942/18192387/74a28eea-7099-11e6-93b3-d7681923a258.png)

You can also find it in the following link:

http://next.openspending.org/api/3/cubes/5df4a7b06a940c992d1c44525daff47b:mex-restructured/facts?cut=administrative_classification_2.Ramo:%2212%22|activity_Modalidad_del.Modalidad_del_Programa:%22S%22|activity_Programa.Programa_Presupuestario:%22251%22|date_2.Ciclo:2016

**Comment by cyberbikepunk** [comment]
> This is exactly how I implemented the algorithm. So everything should be hunky dory @Victordeleon 

Actually that's not the case for 2010: I'm currently extracting the `partida generica` using 3 digits, where I should use four. I will change that.

**Comment by cyberbikepunk** [comment]
@Victordeleon partida generica IDs for 2010 are now 4 digits. Many of these IDs are missing. The missing value situation is:

```
Total: missing 543 catalog IDs to breakdown the "Objeto del Gasto" column
Tables: {'partida_generica': 512, 'concepto': 7, 'partida_específica': 24}
Years: {2010: 519, 2012: 22, 2013: 1, 2015: 1}
```

Please update the [missing ID catalog](https://docs.google.com/spreadsheets/d/1oYasuhA2NvE8yMAQdsqv4BjPckjDn_c26bXXp1v74kQ/edit#gid=1963962081).  I consider this issue as still open.

**Comment by Victordeleon** [comment]
@cyberbikepunk I've already updated almost all the ID's, I'll let you know as soon as I get the missing ones.
