### ISSUE TITLE
Remove unused columns for the merged CSV file

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#18]
Hi @cyberbikepunk 

I vas checking the raw data set loaded on the OS Viewer and I noticed we still have  the following columns of information we don´t need anymore:
- Descripción de Objeto de gasto (we changed it for the disaggregation)
- Objeto de Gasto (we changed it for the disaggregation)
- Descripción de reasignación.
- Reasignación.

So I would kindly ask you to please delete those four columns.

Thank you very much, let me know if you need my help.

Cheers.

**Comment by cyberbikepunk** [comment]
@Victordeleon That is correct: they are in the CSV file but they are not modeled. I will delete them to avoid confusion.

**Comment by cyberbikepunk** [comment]
Implementation is done.
