### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#20]
Hi @cyberbikepunk 

We still have some concepts in the OS viewer which haven't been translated properly, here is the document with the missing translations marked in red:

https://docs.google.com/spreadsheets/d/1AkXyiIR0DYXRSk4_3h5NtUUR_D_1MHvnZTw6xNqdI2U/edit

**Comment by cyberbikepunk** [comment]
Issue moved to [OpenSpending](https://github.com/openspending/openspending/issues/1082).
