### ISSUE TITLE
New file for 2016:2016_2T_Gasto_OS.csv

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#21]
Hi @cyberbikepunk 

We also have an update in the information for 2016 in our shared drive.I uploaded the data both in csv and in excel (in the excel file you find the columns with new info in yellow, both files are named “2016_2T_Gasto_OS”). Loic, do you think we can have the deployment of the update in catalogs plus this new info by tomorrow? so we can present the info to superiors late tomorrow and also start checking for full integrity of the information. We are going to have an executive meeting about the topic. 

Link to the shared drive: https://drive.google.com/drive/folders/0BwvForvqRxfTUnB2SG54cEFSNlk

**Comment by cyberbikepunk** [comment]
@Victordeleon I will do my best. I hope the new file doesn't hold any surprises.
