### ISSUE TITLE
Name of the last file and viewer

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#22]
Hi @cyberbikepunk 

can you please confirm the name of our last file and viewer? It would be the best if we could name this big data base “Presupuesto México 2008-2016”, so it has that “final” deployment name. And do you have the correct, latest, link for us to check thoroughly?

**Comment by cyberbikepunk** [comment]
@Victordeleon it's [here](http://next.openspending.org/viewer/5df4a7b06a940c992d1c44525daff47b:mex-restructured).

**Comment by Victordeleon** [comment]
Hi @cyberbikepunk 

Right now the name is "Mexican Federal Budget 2010-2016 restructured", so we would like to ask you to change both the raw data source and the viewer's name  to “Presupuesto México 2008-2016”

We would also ask you to please remove the folowing text beneath the title: 
Solves issues #3, #4 and #9 on https://github.com/os-data/mexican-federal-budget/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed

Cheers.

**Comment by cyberbikepunk** [comment]
Hi @Victordeleon: It's not currently possible to change the name but I will give the correct title in my next uploads.
