### ISSUE TITLE
Column names: use official column names + add descriptions and titles

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#23]
Hi @cyberbikepunk 

Another question, is there a way to still add the information that was supposed to be input here?

![image](https://cloud.githubusercontent.com/assets/17733942/18153473/3a7a2b96-6fc3-11e6-9ef1-2e794d67ed78.png)

For all our columns? We can have the info by tomorrow in the format that is best for you and think is important to have the full metadata uploaded pre-lunch.

**Comment by cyberbikepunk** [comment]
@Victordeleon Please provide a JSON file specifying the description fields for each column.

**Comment by Victordeleon** [comment]
Of course @cyberbikepunk I'll work it today.

**Comment by cyberbikepunk** [comment]
Quoting @Victordeleon 

> Apart from adding the descriptions to the budget headers, we were wondering if we could change the backend headers in the OS viewer, as in the next image

![image001 1](https://cloud.githubusercontent.com/assets/1629834/18197386/12fe41da-70f7-11e6-9236-ba29563b367a.jpg)

> The thing is that we would like to change all the headers in the OS Packager and the downloadable data base, without modifying the headers we have in the OS viewer. Changing the headers for the downloadable data base would allow its users to cross the information with other data bases from the Ministry of Finance, because the headers would be the same in all of them.
> 
> The adjunct [document](https://docs.google.com/spreadsheets/d/1SPHvXa9Neyvs4j-yx_ucUVekBuAMVSaFYI-08qNmX7M/edit#gid=349523141) is a preliminary version (still needs revision) of the definitions and the headers, but we would appreciate if you check it out so we can attend the matter during our next meeting.

**Comment by cyberbikepunk** [comment]
@Victordeleon I've got "bad news" for you: `description` is not used at the moment in the Veiwer. I talked with @kravets-levko, our front-end developer to confirm this. I filed an [issue in the OpenSpending repository](url).

**Comment by cyberbikepunk** [comment]
> The thing is that we would like to change all the headers in the OS Packager and the downloadable data base, without modifying the headers we have in the OS viewer. 

@Victordeleon this is done by providing the `title` field in the column boxes. I make it happen in the next data deploy.
