### ISSUE TITLE
Missing Federal Programs

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#27]
Hi @cyberbikepunk 

In the data base we have a programa presupuestario called "PROSPERA". 
In 2016 OR 2015 you can filter it by:
Ramo = 20
Modalidad del programa presupuestario = S
Programa presupuestario = 72

We used those filters in the OS viewer and couldn´t find it. It is important that it appears because this is one of the biggest and most know federal programs.

Here is a reproduction:

http://next.openspending.org/viewer/embed/treemap/5df4a7b06a940c992d1c44525daff47b:mexican-federal-budget-2010-to-2016-iteration-1?lang=es&measure=Aprobado.sum&groups%5B%5D=administrative_classification_2.Ramo&filters%5B%5D=administrative_classification_2.Ramo%7C20&filters%5B%5D=activity_Modalidad_del.Modalidad_del_Programa%7CS&filters%5B%5D=date_2.Ciclo%7C2015&order=Aprobado.sum%7Cdesc

**Comment by cyberbikepunk** [comment]
@Victordeleon For _sure_ the  "PROSPERA Programa de Inclusión Social" entry is there. I can drill-down to in the tree-map for example. But I noticed that the IDs for `Programma de Presupuestario`  are not unique and might cause problems. I'm investigating this.

**Comment by cyberbikepunk** [comment]
Closing: see #19
