### ISSUE TITLE
Urgent: issues avoiding us to merge the pipeline

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#29]
Hey @cyberbikepunk 

Esteban Regules tried merge the pipeline in the repositories "mexican-federal-budget" and "cyberpunk/mexico" but wasn't able due to some errors that happened.
1. In relation to "cyberpunk-mexico" it seems that the repository didn´t accept the pipeline because it didn´t accept negative numbers. The pipeline was merging well until it reached 2013, where the data starts having negative numbers that refer to some Ramo's debt. 

![image](https://cloud.githubusercontent.com/assets/17733942/18222531/e98fe0c4-715f-11e6-9e27-da87e1773ffe.png)
1. In relation to "mexican-federal-budget" Esteban comments that the issue seems to be with a library that cannot be found.

![image](https://cloud.githubusercontent.com/assets/17733942/18222548/3c93635e-7160-11e6-81ec-9303124fb31e.png)

So, we would appreciate if you helped us as soon as posible to solve this issues so we can proceed to merge the pipeline and run some tests in the information (we got very few days left for the launch).

I'll adjunct files for both issues in the branch MX-budget-pipeline from this repository so it's easier for you to find out the errors that aren´t allowing us to merge the pipeline.

Thank you very much Loic.

**Comment by cyberbikepunk** [comment]
Number 2 is fixed @Victordeleon: I removed the dependency. Just pull the changes from master.

**Comment by cyberbikepunk** [comment]
@Victordeleon I can't help you with number problem 1 unless I have the data myself. Can you upload the new files to google drive?

**Comment by Victordeleon** [comment]
@cyberbikepunk this is the part of the data base that presented the issue, you can find it in the following link https://drive.google.com/drive/folders/0B4LXWhNL4TpoaDRqYzNETDJsa28

**Comment by cyberbikepunk** [comment]
@Victordeleon I ran the [new CP_2013.csv file](https://drive.google.com/drive/folders/0B4LXWhNL4TpoaDRqYzNETDJsa28) through the pipeline without any problems, using `encoding='cp850'`.
