### ISSUE TITLE
Missing entries in filter drop-down

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#3]
Some dimensions, such as `Funcion` have non-unique global IDs, although IDs are indeed unique for each sub-category. Since filters rely on IDs, not all entries are displayed and there is no search box to search for the missing ones. 

The last iteration of the deployment fixed the `Funcion` filter display by ditching the `Funcion ID` altogether and using the `Descripcion de Funcion` as the ID itself. The result is:

![missing_items_in_filter](https://cloud.githubusercontent.com/assets/1629834/18001558/c9f89ac6-6b83-11e6-9227-9111cd92b88c.png)

I think this is not the way to go however. And this is not the the only place where the problem occurs. `Subfuncion` has the same problem:

![missing_items_in_filter_2](https://cloud.githubusercontent.com/assets/1629834/18002219/caf2a446-6b86-11e6-9cf6-6d7983aa4d93.png)

As seen above, not only are there missing IDs, but there are also duplicate items. I suggest that this be taken care of in the pre-processing pipeline **by prefixing each hierarchical classification level with its parent IDs** to ensure uniqueness.

**Comment by akariv** [comment]
@cyberbikepunk  why not do the same for the `Subfuncion` as well - that is: ditch the IDs and use just the descriptions?
(I agree that prefixing is the better way to go but might be more complicated)

**Comment by cyberbikepunk** [comment]
@akariv In the end I prefixed the IDs.
