### ISSUE TITLE
OS Viewer embeded URL 

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#33]
Hey @cyberbikepunk hope your're doing all right.

I wanted to kindly ask you to please send us a new embedded URL for the OS Viewer.

Right now we have the following visualization from the previous embedded URL you sent us:

![image](https://cloud.githubusercontent.com/assets/17733942/18294933/bd325844-7462-11e6-8a06-6de17fbd6d02.png)

So we would like to ask you to please send us a new link without the OS Viewer header, since normal users of the viewer won't be loggin in or upload data. The idea is that it can look like this:

![image](https://cloud.githubusercontent.com/assets/17733942/18294980/25e359ce-7463-11e6-9273-577a6c56c2cc.png)

Thank you very much.

**Comment by akariv** [comment]
http://next.openspending.org/viewer/embed/5df4a7b06a940c992d1c44525daff47b:cp-mexico?lang=es

@cyberbikepunk please confirm.

**Comment by cyberbikepunk** [comment]
yes
