### ISSUE TITLE
Full data set download

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#34]
Hey @cyberbikepunk 

I just downloaded the mexican federal merged budget available at the OS Viewer, and I'm still getting some weird characters when I open the csv, like in the following image.

![image](https://cloud.githubusercontent.com/assets/17733942/18302792/5aa96f86-749f-11e6-8584-6300b306e9e0.png)

I would ask you if you could check this matter please for the new upload.

**Comment by akariv** [comment]
The resulting CSV should be opened using UTF-8 encoding - as far as I know
Excel doesn't handle encodings very well, so you're better off with
LibreOffice / pages / Google Docs etc.

**Comment by cyberbikepunk** [comment]
I checked the csv outputs and they seem okay
