### ISSUE TITLE
Update column descriptions

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#36]
Hey @cyberbikepunk 
There were some actualizations in the last data base that affected the information we had on the data dictionary (the document we used for the descriptions and tags for the downloadable data base), so we would like to kindly ask you to please actualize the descriptions and titles. I replaced the data dictionary at google drive and marked with color the changes it had. 

You can find the data dictionary in the following link:

https://docs.google.com/spreadsheets/d/1L7ADTYh9-D5kzyhxGSNK3FRvoPJvIN6xJcnAV0P9lkY/edit#gid=912235282

Thanks.

**Comment by cyberbikepunk** [comment]
fixed in pipeline run 19.
