### ISSUE TITLE
Remove hierarchy at the base "Proyecto de Presupuesto de Egresos 2017"

### ISSUE THREAD

**Issue by julioaleman** [os-data/mexican-federal-budget#40]
Could you please remove the hierarchy of the mappping that´s appears as unknown in the base "Proyecto de Presupuesto de Egresos 2017"

![desconocido](https://cloud.githubusercontent.com/assets/18603729/18564775/b8551e6e-7b52-11e6-8068-8f087de58caf.PNG)

**Comment by cyberbikepunk** [comment]
@julioaleman This "unknown" hierarchy has data. What is this data?

**Comment by julioaleman** [comment]
@cyberbikepunk The information is Institutional Activity in spanish "Actividad Institucional", if is easier for you only change the label for the data.
Thanks a lot.

**Comment by cyberbikepunk** [comment]
@julioaleman @Victordeleon @akariv it appears that the pipeline has not been configured properly: this is not the only mistake in the column mapping. The filters should show column display names, not column names from the orginal CSV file. Unfortunately you haven't saved and pushed the pipeline iteration branch so it's hard to diagnose. I'd have to run the pipeline again in a backwards compatible way, which could be tricky.

**Comment by cyberbikepunk** [comment]
There is overlap/confusion with issue #41. I'm tempted to re-define the these 2 issues along the following lines:

1) Non-unique keys in the `Activities` hierarchy need to be prefixed
2) Column mapping issues: the pipeline needs proper configuration for the new 2017 dataset and possibly a new model is required. It's not clear if this can be done in a backwards compatible way.

@julioaleman @Victordeleon @akariv @auramartinez: does everyone agree with this? Can I rename the issues?

**Comment by Victordeleon** [comment]
Hey @cyberbikepunk

Regarding point 1: I'm just worried about what prefixed would mean.
We need Ramo>Modalidad>Programa Presupuestario to have unique keys at the programa presupuestario level although we cannot allow their concatenation to be visualized in the viewer or in the data base. 

Regarding point 2: I think it's ok to redefine it that way.

**Comment by cyberbikepunk** [comment]
@Victordeleon @julioaleman @auramartinez

I think that we the introduction of partial IDs (prioritized [issue #1112 in OS](https://github.com/openspending/openspending/issues/1112)), you should have a long term solution for this. 

Also with the introduction of editable fiscal models ([issue #982 in OS](https://github.com/openspending/openspending/issues/982)) which is coming out very soon, you should be able to rectify mistakes in display names that I can spot from the screenshots.
