### ISSUE TITLE
Incorrect information being shown in viewer for Data Base 2017

### ISSUE THREAD

**Issue by julioaleman** [os-data/mexican-federal-budget#41]
Checking on the viewer for the 2017 dataset we came across with an issue that is showing incorrect information to the public so we find it quite worrisome. 

When filtering per program 57, using the filters, it’s bringing different information that the one in the database, as shown in the screen below:

http://next.openspending.org:80/viewer/embed/treemap/956429a13e5eccb56670201555700320:2017_0?lang=es&measure=PROYECTO_2017.sum&groups[]=administrative_classification_2.ID_RAMO&filters[activity_ID_PP.ID_PP][]=57&order=PROYECTO_2017.sum|desc 

![cap1](https://cloud.githubusercontent.com/assets/18603729/18565852/1953106e-7b57-11e6-9da2-addc22869337.jpg)

Nonetheless, we have identified that it gives you the information for another program with same ID_PP=57, yet the name (Description) is completely different, therefore showing completely wrong information. 

![cap2](https://cloud.githubusercontent.com/assets/18603729/18565871/27032cd0-7b57-11e6-858f-b1d2957621c3.jpg)

Let’s please address it as our first topic in our call on Monday.

**Comment by cyberbikepunk** [comment]
@julioaleman @Victordeleon @akariv 

Quoting @auramartinez on the problem of non-unique keys: 

> Ramo, Modalidad and Programa Presupuestario.
> i.e.: the program we are discussing, PROSPERA is in Ramo 11, 12 and 20, and in all has the same modalidad S and Program ID, 72. So it should be shown in the 3 ramos,, if we build the unique ID, it would be:
> 11S072
> 12S072
> 20S072
> And each program has different budget composition.

I have a question: in first database, the categories were mapped differently. We had:

Activities: `Modalidad` > `Programa Presupuestario`
Administrative: `Ramo` > `Unidad Responsable`

Also: `Actividad Institucional` was the 4th level of the functional classification and now it's an indenpendant classifier. 

Could we clarify this?

**Comment by cyberbikepunk** [comment]
@Victordeleon @julioaleman @auramartinez

I think that we the introduction of partial IDs (prioritized [issue #1112 in OS](https://github.com/openspending/openspending/issues/1112)), you should have a long term solution for this.

**Comment by auramartinez** [comment]
Soon would mean about next week? Or what time frame are we expecting?

Enviado desde mi iPhone

**Comment by Victordeleon** [comment]
Hey @cyberbikepunk quoating @akariv  

>  We already have in the OS type system two kinds of code types: 'full' and 'partial', where full denotes a complete code (i.e. the 'XX-YY' form) and partial denotes the partial code (i.e. the 'YY' form).
> Currently we don't treat these two types differently, but we should. During the loading process, we need to convert the partial 'YY' values to full 'XX-YY' ones.

I'm not sure if I'm understanding correctly so I rather ask. Treating differently partial and complete codes would mean to convert partial codes into complete codes? Wouldn't it be like a concatenation?
And if that's the case, would the concatenation be visible in the viewer and the data set or would it only be a backend measure? 

We would appreciate very much if you could explain us what the solution would be by referring the issue to how we would have to import the information in the packager.

**Comment by akariv** [comment]
In the case that the code columns have matching display-name columns (as is the case with your dataset if I'm not mistaken), then there will be no visible change in the viewer.
