### ISSUE TITLE
Maps graph 2008-2016 and 2017 OS Viewer

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#44]
The maps graph doesn´t seem to be working, I tried “Aprobado” in Measures, “Entidad Federativa” in “Ubicación”, but no visualization is appearing. 
http://next.openspending.org:80/viewer/embed/map/956429a13e5eccb56670201555700320:2017_0?lang=es&measure=PROYECTO_2017.sum&groups[]=geo_source_2.ID_ENTIDAD_FEDERATIVA&order=PROYECTO_2017.sum|desc

**Comment by cyberbikepunk** [comment]
@Victordeleon @auramartinez the map view is not yet available. @akariv Do we want to remove the icon so that it doesn't raise confusion. And transfer the issue to OS?
