### ISSUE TITLE
Pivot Tables 2008-2016 and 2017 OS Viewer

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#46]
Pivot tables seem to be working fine in regards to the rows and columns you can select, and the amounts displayed are coherent with the data bases. The issue detected in this matter is that “Modalidad del Programa Presupuestario” appears at the rows by default. Therefore the correction proposal would be that the option “Modalidad del Programa Presupuestario” in the “Filas” options appears open so the user can easily know which of the options is already activated. 
Also, the downloadables .CSV in the pivot tables come with the weird characters.
http://next.openspending.org:80/viewer/embed/pivottable/5df4a7b06a940c992d1c44525daff47b:mexico-presupuesto?lang=es&measure=Adefas.sum&rows[]=activity_Modalidad_del.Modalidad_del_Programa&columns[]=date_2.Ciclo&order=Adefas.sum|desc

**Comment by cyberbikepunk** [comment]
The second part of this question sounds like #50. 

@akariv this is a front-end issue i think. Can we migrate it to OS?
