### ISSUE TITLE
OS Viewer and Raw Data base concatenations

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#49]
Raw data base: the raw data base shouldn’t have concatenations in its columns. This is specially important since it modifies the information in a way that is not contemplated in the dictionary.
In the OS Viewer: the concatenations made in the filters for “Función”, “Subfunción” and “Actividad Institutional” are not correct and are not coherent with our data dictionary descriptions. We should avoid this tipe of concatenations by a solution like the one mentioned above.

**Comment by cyberbikepunk** [comment]
Functional category ID prefixing has been dropped. This issue is fixed.
