### ISSUE TITLE
The Sankey diagram does not work

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#5]
Aura mentioned that the Sankey diagram was not available in the viewer for the [`mex` dataset](http://next.openspending.org/viewer/5df4a7b06a940c992d1c44525daff47b:mex?lang=en).  
![sankey_fail](https://cloud.githubusercontent.com/assets/1629834/18003083/e9b3908e-6b8b-11e6-86f3-906d884f2ddb.png)

This a little too vague. Could Aura or Victor please share a viewer-link to the problem?

**Comment by akariv** [comment]
@cyberbikepunk please consult with levko on how to use this vis.

**Comment by Victordeleon** [comment]
@cyberbikepunk @akariv 

It seems to be working, although it takes long to visualize and it's not very clear. In the reproduction I chose Aprobado in Measures and Budget Line ID in Hierarchies. Here is a reproduction for the sankey
http://next.openspending.org:80/viewer/embed/sankey/5df4a7b06a940c992d1c44525daff47b:mex-restructured?lang=en&measure=Aprobado.sum&groups[]=budget_line_id_2.Clave_de_cartera&order=Aprobado.sum|desc

In the next reproduction I chose "Aprobado" and "Functional Classification", filtered by 2016. Same as the previous one, it takes too long wo activate, which can give the impression that it isn´t working. Adding the filter makes it quicker:

http://next.openspending.org:80/viewer/embed/sankey/5df4a7b06a940c992d1c44525daff47b:mex-restructured?lang=en&measure=Aprobado.sum&groups[]=functional_classification_2.Grupo_Funcional&filters[]=date_2.Ciclo|2016&order=Aprobado.sum|desc

**Comment by cyberbikepunk** [comment]
@akariv The above links return a 404. Any ideas why?
