### ISSUE TITLE
Importing unicode CSV files in Excel

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#50]
We still have weird characters in the downloadable csv data set. We understand that they can appear when you open the file as an xlsx in a Excel spreadsheet, but we’ve been importing them as text, and that normally works to avoid the weird characters, although this is not the case. We ask for the data set to have normal characters, thinking it will be opened in an excel file, because that’s the program that most users normally have on default in their computers. 

![image](https://cloud.githubusercontent.com/assets/17733942/18715653/ac4c58bc-7fdf-11e6-80ee-2fa9e1ea1cea.png)

I've tried opening in Excel both the 2008-2016 and the 2017 data bases using the same procedures, meaning I imported them as text files into a spreadsheet. The issue only occurs in the 2008-2016 data base.

**Comment by cyberbikepunk** [comment]
@Victordeleon @auramartinez:

The file is encoded in 'utf-8' which is basically as standard as it gets. Unfortunately Excel seems to open file assuming the local encoding (which would be ISO-8859-1, judging from the characters you're showing). May I suggest that you look at this tutorial on [how to import Unicode CSV files into Excel](https://help.tune.com/marketing-console/how-to-import-a-unicode-csv-to-excel/). Unless @akariv suggests otherwise, i would like to close this issue.

**Comment by Victordeleon** [comment]
Hey @cyberbikepunk thanks for the tutorial, but that's exactly the process we normally use to open csv files in Excel (we don't double click the downloaded file). The real issue is not that we learn the process, but that normal users of the OS Viewer very probably will use Excel and will not know how to apply the correct process. The reason that we insist on this issue is that normal cititzens who use the plattform very likely won´t know how to open the file correctly.

The weird thing is that the Unknown characters only appear for the 2008-2016 data set and not for the 2017 one (you won't get unknown characters even if you just double click the csv file to open it). So we would like it to be the same for the 2008-2016 data set.

**Comment by akariv** [comment]
Can you please make sure that the original CSV files open correctly in
Excel before uploading? we've seen some strange encodings being used in
some of the source files.

**Comment by Victordeleon** [comment]
@akariv should they have any specific encoding?

**Comment by akariv** [comment]
windows-1252 is a good choice, but it's best to test it out locally
obviously.
