### ISSUE TITLE
Descriptions not available in the OS Viewer

### ISSUE THREAD

**Issue by Victordeleon** [os-data/mexican-federal-budget#57]
Even though there is an option for adding descriptions in the packager:

![image](https://cloud.githubusercontent.com/assets/17733942/18999115/976ff916-8701-11e6-9f55-d650d47e73b7.png)

This option isn´t really working because there is nowhere in the OS Viewer that reflects the input for this field. This way, we would ask that to make Description available for each of the concepts of the packager, so citizens can know what the concepts mean. It is very important that this issue is solved through the packager so we independently do any actualizations we wish for.

**Comment by pwalsh** [comment]
The Viewer, by design, does not show every possible piece of data (that would be bad UX). 

We don't intend to expose descriptions in the Viewer at this time, but they are of course in the API, for use in custom visualisations.
