### ISSUE TITLE
Migrate the pipeline to datapackage-pipelines

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#6]
As it stands, the pipeline is a `jupyter` notebook. For several reasons, including speeding up pipeline runs during the development phase and future automation of quarterly budget updates, I would like to migrate code to the [`luigi` framework](http://luigi.readthedocs.org/).

**Comment by akariv** [comment]
We will be using the `os-pipelines` module once it's ready (soon)

**Comment by cyberbikepunk** [comment]
I changed the title to reflect that @akariv

**Comment by cyberbikepunk** [comment]
I'm closing this and progress with the new pipeline framework can be [followed here](https://github.com/openspending/os-data-importers/tree/master/america/mexico).
