### ISSUE TITLE
Viewer crashes

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#8]
Quoting Aura:

> The viewer seems to have some functionality issues, several times the web-page crashes when changing options or filters. 

![unresponsive_viewer](https://cloud.githubusercontent.com/assets/1629834/18004166/6c0b3f22-6b92-11e6-81c1-31697696f943.png)

Are the crashes reproducible? If so please provide a viewer-link and a description of the UX interaction that causes the crash.

**Comment by Victordeleon** [comment]
Hi @cyberbikepunk 
I haven't had this issue again, so I'm not able to reproduce. If it happens then I'll post it here immediately.
