### ISSUE TITLE
Data structure update: Objeto del Gasto

### ISSUE THREAD

**Issue by cyberbikepunk** [os-data/mexican-federal-budget#9]
Quoting Aura:

> We’re going to have a small change in the data structure that will imply slight changes in the modeling in order to show more complete and homogeneous information. We’re going to add the following 8 columns to the data set, which correspond to the disaggregation of `Objeto del Gasto`.
1. `ID_CAPITULO`
2. `DESC_CAPITULO`
3. `ID_CONCEPTO`
4. `DESC_CONCEPTO`
5. `ID_PARTIDA_GENERICA`
6. `DESC_PARTIDA_GENERICA`
7. `ID_PARTIDA_ESPECIFICA`
8. `DESC_PARTIDA_ESPECIFICA`

> This breakdown of `Objeto del Gasto` belongs to the `Clasificación Económica` category, which classifies the Mexican Federal Budget according to what is bought with the money. The ID-description catalog for the breakdown is [here](https://drive.google.com/file/d/0BwvForvqRxfTVkUtNGRTbUFPTFE/view?usp=sharing).

**Comment by cyberbikepunk** [comment]
Aura provided an explanation on how to operate the column breakdown:

![objeto_breakdown](https://cloud.githubusercontent.com/assets/1629834/18004894/1e54339c-6b97-11e6-8d72-c14af227b513.jpg)

**Comment by cyberbikepunk** [comment]
I uploaded a list of missing catalog entries that I need to be able to run the breakdown on [google drive](https://docs.google.com/spreadsheets/d/1h5T2ycf-kBRr_A_fZ7yjuI8ZYjpFUln00mrMi3wgHhA/edit#gid=2075871983). 

By the way, here is the [global reference catalog](https://docs.google.com/spreadsheets/d/1dxm6OOuCUYV196hs592TI4pCGVcBxh6oDEwS0OqwGMQ/edit#gid=1676585081) for the mexican federal budget.

**Comment by cyberbikepunk** [comment]
Quoting Aura's mail:

> Hope my email finds you well. We looked in all the old catalogs and [found most of the missing values](https://docs.google.com/spreadsheets/d/1h5T2ycf-kBRr_A_fZ7yjuI8ZYjpFUln00mrMi3wgHhA/edit#gid=2075871983).

**But there are still 24 missing**:

15404 | partida_especifica
15406 | partida_especifica
15904 | partida_especifica
15905 | partida_especifica
15906 | partida_especifica
15907 | partida_especifica
15908 | partida_especifica
15909 | partida_especifica
15911 | partida_especifica
15912 | partida_especifica
33802 | partida_especifica
34102 | partida_especifica
34502 | partida_especifica
35103 | partida_especifica
36301 | partida_especifica
37702 | partida_especifica
38502 | partida_especifica
39102 | partida_especifica
39802 | partida_especifica
44113 | partida_especifica
48103 | partida_especifica
56702 | partida_especifica
61701 | partida_especifica
75201 | partida_especifica

> Can you help us by telling us in which year did you find them? That way we can re-check individually and if not, try with the area responsible for the catalogs. Thanks tons!

**Comment by cyberbikepunk** [comment]
Aura, I added a [new sheet](https://docs.google.com/spreadsheets/d/1h5T2ycf-kBRr_A_fZ7yjuI8ZYjpFUln00mrMi3wgHhA/edit#gid=926473283) in the Google spreadsheet that specifies the year for each missing catalog entry.

**Comment by auramartinez** [comment]
Here I am @cyberbikepunk :) will try to b on the loop but please help me by tagging me wherever needed :)
